language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=origin/master

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - sudo apt-get install -qq beanstalkd
  - sudo ./beanstalkd -l 127.0.0.1 -p 11300
 
script: phpunit --configuration phpunit.xml.dist
